always_for_in = true
always_use_return = false
margin = 92
remove_extra_newlines = true
short_to_long_function_def = true
indent = 4
style = "sciml"
align_struct_field = true
align_conditional = true
align_assignment = true
align_pair_arrow = true
whitespace_typedefs = true
whitespace_ops_in_indices = true
